apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dstrategies-canary
  namespace: user12-gitops-argocd
spec:
  destination:
    name: ''
    namespace: user12-canary
    server: 'https://kubernetes.default.svc'
  source:
    path: canary
    repoURL: https://github.com/romerobu/dstrategies-app-deployment
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
